name: Web UI Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set permission
        run: chmod +x ./gradlew

      - name: Run UI Tests
        run: ./gradlew test

      # Upload only HTML report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: build/reports/cucumber-html-report.html

      # Upload only JSON report
      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: build/reports/cucumber-report.json