name: Web UI Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set permission
        run: chmod +x ./gradlew

      - name: Run UI Tests
        run: ./gradlew test

      # Upload test report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-test-report
          path: build/reports/tests/test


