name: Web UI Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Give permission to Gradle
        run: chmod +x ./gradlew

      - name: Run UI Tests
        run: ./gradlew clean test

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-html-report
          path: target/web-report.html

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-json-report
          path: target/web-report.json

